---
# config.yml
zendesk:
  domain: ukraineesc1661880008.zendesk.com
  tags: "cfht_bot" 
  pageSize: 50
  createdAt: "2022-01-01"
  targetPrefix: "10908488781723"
  srcPrefix: "8788277706395"
redis:
  url: "redis://127.0.0.1:6379"
